Repository colinwilson/lotusdocs, pull requests merged in 2025-01, with the labels that each got.

#194 Fix error messages when running example site with hugo 0.138
  README.md
  config.toml
  exampleSite/content/docs/example-content/mermaid.md
  exampleSite/go.mod
  go.mod
  layouts/_default/baseof.html
  layouts/docs/baseof.html
  layouts/partials/docs/footer/footer-scripts.html
  layouts/partials/docs/head.html
  layouts/partials/docs/head/opengraph.html
  layouts/partials/docs/head/twitter_cards.html
  layouts/partials/docs/top-header.html
  layouts/partials/head.html
  netlify.toml
  theme.toml
Labels: bug

#196 🗑️ remove/replace deprecated .Site.GoogleAnalytics
  layouts/partials/docs/footer/feedback.html
Labels: bug

#159 fix URL in CTA button
  layouts/partials/landing/hero.html
Labels: bug

#120 Add automatic discovery for Atom feeds so it's easier to subscribe to new content on the site
  layouts/partials/docs/head.html
Labels: enhancement

#198 📄 update readme, 🅰️ update material symbol font file & scss config
  README.md
  assets/scss/custom/plugins/icons/_google-material.scss
  static/docs/fonts/material-symbols-outlined.woff2
Labels: improvment

#200 📱 add bluesky to social options
  assets/images/social/bluesky.svg
  layouts/_default/baseof.html
  layouts/docs/baseof.html
  layouts/partials/docs/top-header.html
  layouts/partials/header.html
Labels: improvment
